apiVersion: configmanagement.gke.io/v1
kind: ConfigManagement
metadata:
  name: config-management
spec:
  clusterName: usercluster2
  git:
    syncRepo: git@github.com:ishitac51/acm-poc.git
    syncBranch: 1.0.0
    secretType: none
    policyDir: "demo-1.1a"
